#: import NoTransition kivy.uix.screenmanager.NoTransition
#: import ToggleButtonBehavior kivy.uix.behaviors.ToggleButtonBehavior

MDScreen:
    md_bg_color: self.theme_cls.secondaryContainerColor
    MDNavigationLayout:
        MDScreenManager:
            id: nav_manager
            ScreenCalculator:
            ScreenSettings:

        MDNavigationDrawer:
            id: nav_drawer
            radius: 0, dp(16), dp(16), 0
            MDNavigationDrawerMenu:
                MDNavigationDrawerLabel:
                    text: "Меню"
                    padding: "18dp", 0, "18dp", "4dp"
                    font_style: "Title"
                MDNavigationDrawerDivider:
                MDNavigationDrawerItem:
                    on_release: nav_manager.current = 'menu' ; nav_drawer.set_state("toggle")
                    #nav_manager.transition = NoTransition() ;
                    MDNavigationDrawerItemLeadingIcon:
                        icon: "calculator"
                    MDNavigationDrawerItemText:
                        text: "Калькуляторы"
                MDNavigationDrawerItem:
                    on_release: nav_manager.current = 'settings' ; nav_drawer.set_state("toggle")
                    MDNavigationDrawerItemLeadingIcon:
                        icon: "cog"
                    MDNavigationDrawerItemText:
                        text: "Настройки"
                MDNavigationDrawerDivider:

<ScreenCalculator@MDScreen>:
    name: "menu"
    MDScreenManager:
        id: menu_manager

        MDScreen:
            name: 'calculator'
            MDBoxLayout:
                orientation: 'vertical'

                TopMenu:

                ScrollView:
                    ScrollMenu:
                        Title:
                            text: "Калькуляторы"
                        MDButton:
                            on_release: menu_manager.current = "massloss"
                            MDButtonText:
                                text: "Расчёт убыли массы тела"    
                        MDButton:
                            on_release: menu_manager.current = "entfunc"
                            MDButtonText:
                                text: "Расчёт энтерального питания\nпо функциональной вместимости желудка"
                        MDButton:
                            on_release: menu_manager.current = "entzayaz"
                            MDButtonText:
                                text: "Расчёт энтерального питания\nпо формуле Г.И. Зайцевой"
                        MDButton:
                            on_release: menu_manager.current = "entenergy"
                            MDButtonText:
                                text: "Расчёт энтерального питания\nпо энергетическому способу"
                        MDButton:
                            on_release: menu_manager.current = "parent"
                            MDButtonText:
                                text: "Расчёт парентерального питания"
                        MDButton:
                            on_release: menu_manager.current = "neutroindex"
                            MDButtonText:
                                text: "Расчёт нейтрофильного индекса"
                        MDButton:
                            on_release: menu_manager.current = "kurosurf"
                            MDButtonText:
                                text: "Расчёт дозы куросурфа"
                        MDButton:
                            on_release: menu_manager.current = "cofe"
                            MDButtonText:
                                text: "Расчёт дозы кофеина"
                        MDButton:
                            on_release: menu_manager.current = "dofamine"
                            MDButtonText:
                                text: "Расчёт дозы дофамина"
                        MDButton:
                            on_release: menu_manager.current = "metro"
                            MDButtonText:
                                text: "Расчёт дозы метронидазола"
                        MDButton:
                            on_release: menu_manager.current = "ampi"
                            MDButtonText:
                                text: "Расчёт дозы ампициллина"
                        MDButton:
                            on_release: menu_manager.current = "genta"
                            MDButtonText:
                                text: "Расчёт дозы гентамицина"
                        Title:
                            text: "Шкалы"
                        MDButton:
                            on_release: menu_manager.current = "silverman"
                            MDButtonText:
                                text: "Шкала Сильвермана"
                        MDButton:
                            on_release: menu_manager.current = "downes"
                            MDButtonText:
                                text: "Шкала Даунса"
                        MDButton:
                            on_release: menu_manager.current = "ballard"
                            MDButtonText:
                                text: "Шкала Балларда"

                MDTopAppBar:
                    size_hint_y: .2
                    #MDTopAppBarLeadingButtonContainer:
                        #MDActionTopAppBarButton:
                            #icon: "magnify"
                    #MDTopAppBarTitle:
                        #text: "Поиск..."
        ScreenMassLoss:
        ScreenEntFunc:
        ScreenEntZayaz:
        ScreenEntEnergy:
        ScreenParent:
        ScreenNeutroIndex:
        ScreenKurosurf:
        ScreenCofe:
        ScreenDofamine:
        ScreenMetro:
        ScreenAmpi:
        ScreenGenta:
        ScreenSilverman:
        ScreenDownes:
        ScreenBallard:

<ScreenSettings@MDScreen>:
    name: 'settings'
    MDBoxLayout:
        orientation: 'vertical'

        TopMenu:

        ScrollView:
            ScrollMenu:
                Header:
                    text:"Второй скрин"
                                   
        MDTopAppBar:
            size_hint_y: .2

<TopMenu@MDTopAppBar>:
    size_hint_y: .2
    MDTopAppBarLeadingButtonContainer:
        MDActionTopAppBarButton:
            icon: "menu"
            on_press: app.open_menu()
    MDTopAppBarTitle:
        text: "Медицинский калькулятор"
        pos_hint: {"center_x": .5}
        font_style: "Title"
        role: "medium"
<TopMenu2@MDTopAppBar>:
    size_hint_y: .2
    MDTopAppBarLeadingButtonContainer:
        MDActionTopAppBarButton:
            icon: "arrow-left"
            on_press: app.back_to_menu()
    MDTopAppBarTitle:
        text: "Медицинский калькулятор"
        pos_hint: {"center_x": .5}
        font_style: "Title"
        role: "medium"


<TileContainer@MDSmartTileOverlayContainer>:
    adaptive_height: True
    padding: 0, "8dp"
    spacing: "8dp"
<ImageCheckbox@MDCheckbox>:
    pos_hint: {"center_y": .1, "center_x": 0}
<SmartMenu@MDGridLayout>:
    spacing: "6dp"
    size_hint_y: None
    rows: 3
    cols: 3
<SubMenuTitle@MDLabel>:
    adaptive_height: True
    padding: "12dp", 0, 0, 0       
<ScrollMenu@MDGridLayout>:
    padding: "12dp"
    spacing: "12dp"
    cols: 1
    adaptive_height: True
<Header@MDLabel>
    font_style: "Headline"
    adaptive_height: True
<Title@MDLabel>:
    font_style: "Title"
    adaptive_height: True
    padding: "6dp", 0, 0, 0  
<MDNavigationBar>:
    size_hint_y: .2
    padding: "10dp"
    spacing: "10dp"
<CountBar@MDNavigationItemLabel>:
    text: "Вычислить"
    pos_hint: {"center_x": .5, "center_y": 0}
<ClearBar@MDNavigationItemLabel>:
    text: "Очистить форму"
    pos_hint: {"center_x": .5, "center_y": 0}
<BottomMenu@MDNavigationBar>:
    MDNavigationItem:
        on_release: app.clear_calculator()
        active: False
        ClearBar:

<ScreenMassLoss@MDScreen>:
    name: "massloss"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт убыли массы тела"
                SubMenuTitle:
                    text: "Масса при рождении (г)"
                MDTextField:
                    id: mass1
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_mass()
                SubMenuTitle:
                    text: "Настоящая масса (г)"
                MDTextField:
                    id: mass2
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_mass()
                SubMenuTitle:
                    text: "Потеря массы тела" 
                MDTextField:
                    id: result
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenKurosurf@MDScreen>:
    name: "kurosurf"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы куросурфа\n80мг/мл (120мг/фл)"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: dose1
                        group: "dose"
                        on_press: app.count_kurosurf() ; dose1.active = True
                        active: True
                    MDLabel:
                        text: "Стартовая доза 200мг/кг"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: dose2
                        group: "dose"
                        on_press: app.count_kurosurf() ; dose2.active = True                        
                    MDLabel:
                        text: "Доза для повторного введения 100мг/кг"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_kurosurf()
                SubMenuTitle:
                    text: "Результат" 
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True
                MDTextField:
                    id: result3
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenCofe@MDScreen>:
    name: "cofe"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы кофеина-бензоата натрия\n200 мг/мл"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: cofe1
                        group: "cofe"
                        on_press: app.count_cofe() ; cofe1.active = True  
                        active: True
                    MDLabel:
                        text: "Нагрузочная доза 20 мг/кг"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: cofe2
                        group: "cofe"
                        on_press: app.count_cofe() ; cofe2.active = True                        
                    MDLabel:
                        text: "Поддерживающая доза 5 мг/кг"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_cofe()
                SubMenuTitle:
                    text: "Результат" 
                MDTextField:
                    id: result
                    mode: "outlined"
                    readonly: True 

        BottomMenu:

<ScreenDofamine@MDScreen>:
    name: "dofamine"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы дофамина\n40 мг/мл"

                SubMenuTitle:
                    text: "Доза (мкг/кг/мин)"
                MDTextField:
                    id: dofa
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_dofamine()
                    MDTextFieldHintText:
                        text: "Стартовая доза от 5 мкг/кг/мин"
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_dofamine()
                SubMenuTitle:
                    text: "Результат" 
                MDTextField:
                    id: result
                    mode: "outlined"
                    readonly: True 

        BottomMenu:

<ScreenMetro@MDScreen>:
    name: "metro"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы метронидазола\n500 мг/100 мл"
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_metro()
                SubMenuTitle:
                    text: "Суточная доза (мг/кг/сут)"
                MDTextField:
                    id: dose
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_metro()
                SubMenuTitle:
                    text: "Кратность введения"
                MDTextField:
                    id: crat
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_metro()
                SubMenuTitle:
                    text: "Результат"
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenAmpi@MDScreen>:
    name: "ampi"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы ампициллина"
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_ampi()
                SubMenuTitle:
                    text: "Суточная доза (мг/кг/сут)"
                MDTextField:
                    id: dose
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_ampi()
                SubMenuTitle:
                    text: "Кратность введения"
                MDTextField:
                    id: crat
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_ampi()
                SubMenuTitle:
                    text: "Разовая доза в мг"
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Содержание в 1 флаконе"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: flacone1
                        group: "flacone"
                        on_press: app.count_ampi() ; flacone1.active = True   
                        active: True
                    MDLabel:
                        text: "500 мг/фл"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: flacone2
                        group: "flacone"
                        on_press: app.count_ampi() ; flacone2.active = True                           
                    MDLabel:
                        text: "1000 мг/фл"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: flacone3
                        group: "flacone"
                        on_press: app.count_ampi() ; flacone3.active = True                        
                    MDLabel:
                        text: "2000 мг/фл"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                SubMenuTitle:
                    text: "Объём растворителя (мл)"
                MDTextField:
                    id: volume
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_ampi()
                SubMenuTitle:
                    text: "Разовая доза в мл"
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenGenta@MDScreen>:
    name: "genta"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт дозы гентамицина\n40 мг/мл"
                SubMenuTitle:
                    text: "Масса тела ребёнка (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_genta()
                SubMenuTitle:
                    text: "Суточная доза (мг/кг/сут)"
                MDTextField:
                    id: dose
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_genta()
                SubMenuTitle:
                    text: "Кратность введения"
                MDTextField:
                    id: crat
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_genta()
                SubMenuTitle:
                    text: "Результат"
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenNeutroIndex@MDScreen>:
    name: "neutroindex"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт нейтрофильного индекса"
                SubMenuTitle:
                    text: "Миелоциты (%)"
                MDTextField:
                    id: percent1
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_neutroindex()
                SubMenuTitle:
                    text: "Юные нейтрофилы (%)"
                MDTextField:
                    id: percent2
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_neutroindex()
                SubMenuTitle:
                    text: "Палочкоядерные нейтрофилы (%)"
                MDTextField:
                    id: percent3
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_neutroindex()
                SubMenuTitle:
                    text: "Сегментоядерные нейтрофилы (%)"
                MDTextField:
                    id: percent4
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_neutroindex()
                SubMenuTitle:
                    text: "Результат"
                MDTextField:
                    id: result
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenEntFunc@MDScreen>:
    name: "entfunc"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт энтерального питания по функциональной вместимости желудка"
                SubMenuTitle:
                    text: "Масса при рождении (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entfunc()
                SubMenuTitle:
                    text: "День жизни"
                MDTextField:
                    id: day
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entfunc()
                SubMenuTitle:
                    text: "Количество молока на одно кормление:"
                MDTextField:
                    id: result
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenEntZayaz@MDScreen>:
    name: "entzayaz"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт энтерального питания по формуле Г.И. Зайцевой"
                SubMenuTitle:
                    text: "Масса при рождении (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entzayaz()
                SubMenuTitle:
                    text: "День жизни"
                MDTextField:
                    id: day
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entzayaz()
                SubMenuTitle:
                    text: "Суточное количество молока:"
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Число кормлений в сутки"
                MDTextField:
                    id: crat
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entzayaz()
                SubMenuTitle:
                    text: "Количество молока на одно кормление:"
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenEntEnergy@MDScreen>:
    name: "entenergy"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Расчёт энтерального питания по энергетическому способу"
                SubMenuTitle:
                    text: "Масса при рождении (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entenergy()
                SubMenuTitle:
                    text: "День жизни"
                MDTextField:
                    id: day
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entenergy()
                SubMenuTitle:
                    text: "Потребность в энергии (ккал/кг/сут)"
                MDTextField:
                    id: energy
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Суточное количество молока:"
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Число кормлений в сутки"
                MDTextField:
                    id: crat
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_entenergy()
                SubMenuTitle:
                    text: "Количество молока на одно кормление:"
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True

        BottomMenu:

<ScreenParent@MDScreen>:
    name: "parent"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                id: parent_scroll  
                Header:
                    text: "Расчёт парентерального питания"
                Title:
                    text: "Расчёт суточного объёма жидкости"
                SubMenuTitle:
                    text: "Физиологическая потребность (мл/кг)"
                MDTextField:
                    id: physneed
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Масса тела (г)"
                MDTextField:
                    id: mass
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Суточная потребность (мл/сут):"
                MDTextField:
                    id: dayneed
                    mode: "outlined"
                    readonly: True
                Title:
                    text: "Расчёт объёма энтерального питания"
                SubMenuTitle:
                    text: "Энтерально получает:"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: food1
                        group: "food"
                        on_press: app.count_parent()
                        disabled: True if food1.active == True else False
                        active: True
                    MDLabel:
                        text: "Грудное молоко"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: food2
                        group: "food"
                        on_press: app.count_parent()
                        disabled: True if food2.active == True else False
                    MDLabel:
                        text: "Смесь для доношенных"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: food3
                        group: "food"
                        on_press: app.count_parent()
                        disabled: True if food3.active == True else False
                    MDLabel:
                        text: "Смесь для недоношенных"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                SubMenuTitle:
                    text: "Объём разового кормления (мл)"
                MDTextField:
                    id: volumeonetime
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Число кормлений (раз/сут)"
                MDTextField:
                    id: count
                    mode: "filled"
                    input_filter: 'int'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Объём питания на кг массы (мл/кг/сут):"
                MDTextField:
                    id: volumephys
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Объём энтерального питания (мл/сут):"
                MDTextField:
                    id: volumeent
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Углеводов энтерально:"
                MDTextField:
                    id: ugle
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Белка энтерально:"
                MDTextField:
                    id: belki
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Жиров энтерально:"
                MDTextField:
                    id: zhiry
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Калорий энтерально:"
                MDTextField:
                    id: kkal
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Объём препаратов вводимых внутривенно (болюсы) (мл):"
                MDTextField:
                    id: bolus
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Суточная доза жидкости с учетом энтерального питания и болюсов (мл/сут)"
                MDTextField:
                    id: dayneedent
                    mode: "outlined"
                    readonly: True
                Title:
                    text: "Расчёт суточного объема раствора белка"
                SubMenuTitle:
                    text: "Расчетная доза (г/кг)"
                MDTextField:
                    id: dosebelki
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Суточная доза белка вводимая парентерально (г/сут)"
                MDTextField:
                    id: daydosebelki
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Объём 10% раствора аминокислот (мл/сут)"
                MDTextField:
                    id: amino
                    mode: "outlined"
                    readonly: True

                Title:
                    text: "Расчёт суточного объема жировой эмульсии"
                SubMenuTitle:
                    text: "Расчетная доза (г/кг)"
                MDTextField:
                    id: dosezhiry
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Суточная доза жира вводимая парентерально (г/сут)"
                MDTextField:
                    id: daydosezhiry
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Объём 20% эмульсии жиров (мл/сут)"
                MDTextField:
                    id: amulszhiry
                    mode: "outlined"
                    readonly: True
                 
                Title:
                    text: "Расчёт необходимого объема электролитов"
                SubMenuTitle:
                    text: "Расчетная доза натрия (ммоль/кг)"
                MDTextField:
                    id: na_need
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Объём раствора натрия хлорида 0.9% (мл/сут)"
                MDTextField:
                    id: na_dose
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Расчетная доза калия (ммоль/кг)"
                MDTextField:
                    id: k_need
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Объём раствора калия хлорида 4% (мл/сут)"
                MDTextField:
                    id: k_dose
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Расчетная доза кальция (ммоль/кг)"
                MDTextField:
                    id: ca_need
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()

                SubMenuTitle:
                    text: "Выбор кальция:"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: kalz1
                        group: "kalz"
                        on_press: app.count_parent()
                        disabled: True if kalz1.active == True else False
                        active: True
                    MDLabel:
                        text: "глюконата"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: kalz2
                        group: "kalz"
                        on_press: app.count_parent()
                        disabled: True if kalz2.active == True else False
                    MDLabel:
                        text: "хлорида"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                SubMenuTitle:
                    id: kalz_text
                    text: "Объём раствора кальция глюконата 10% (мл/сут)"
                MDTextField:
                    id: ca_dose
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Расчетная доза магния (мг/кг)"
                MDTextField:
                    id: mg_need
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Объём раствора магния сульфата 25% (мл/сут)"
                MDTextField:
                    id: mg_dose
                    mode: "outlined"
                    readonly: True

                Title:
                    text: "Расчёт дозы углеводов (глюкозы)"
                SubMenuTitle:
                    text: "Расчетная доза углеводов (мг/кг/мин)"
                MDTextField:
                    id: ugleneed
                    mode: "filled"
                    input_filter: 'float'
                    on_text: app.count_parent()
                SubMenuTitle:
                    text: "Суточная доза глюкозы (г/сут)"
                MDTextField:
                    id: daydoseugle
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Объём раствора углеводов (мл/сут)"
                MDTextField:
                    id: doseugle
                    mode: "outlined"
                    readonly: True

                SubMenuTitle:
                    text: "Выбор концентраций:"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: conc1
                        group: "conc"
                        on_press: app.count_parent()
                        disabled: True if conc1.active == True else False
                        active: True
                    MDLabel:
                        text: "5% и 10%"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: conc2
                        group: "conc"
                        on_press: app.count_parent()
                        disabled: True if conc2.active == True else False
                    MDLabel:
                        text: "5% и 40%"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: conc3
                        group: "conc"
                        on_press: app.count_parent()
                        disabled: True if conc3.active == True else False
                    MDLabel:
                        text: "10% и 40%"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}

                SubMenuTitle:
                    id: gluk_text1
                    text: "Объём раствора глюкозы 5% (мл/сут)"
                MDTextField:
                    id: gluk1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    id: gluk_text2
                    text: "Объём раствора глюкозы 10% (мл/сут)"
                MDTextField:
                    id: gluk2
                    mode: "outlined"
                    readonly: True

                Title:
                    text: "Расчёт скорости инфузии"
                SubMenuTitle:            
                    text: "Скорость основной инфузии"
                MDTextField:
                    id: speed1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Скорость инфузии жировой эмульсии"
                MDTextField:
                    id: speed2
                    mode: "outlined"
                    readonly: True

                Title:
                    text: "Расчёт концентрации глюкозы в инфузионном растворе"
                SubMenuTitle:            
                    text: "Концентрация глюкозы в инфузионном растворе"
                MDTextField:
                    id: concgluk
                    mode: "outlined"
                    readonly: True

                Title:
                    text: "Расчёт калорийности питания"
                SubMenuTitle:            
                    text: "Калорийность парентерального питания"
                MDTextField:
                    id: kkalparent
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Общая калорийность"
                MDTextField:
                    id: kkalsum
                    mode: "outlined"
                    readonly: True

        MDNavigationBar:
            MDNavigationItem:
                on_release: app.clear_calculator()
                MDNavigationItemLabel:
                    text: "Очистить форму"
                    pos_hint: {"center_x": .5, "center_y": 0}
            MDNavigationItem:
                id: print_button
                on_release: app.print_parent()
                disabled: True
                MDNavigationItemLabel:
                    text: "Заполнить документ"
                    pos_hint: {"center_x": .5, "center_y": 0}

<ScreenSilverman@MDScreen>:
    name: "silverman"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Шкала Сильвермана"
                SubMenuTitle:
                    text: "Движения грудной клетки" 
                MDList:
                    MDListItem:
                        height: silver_text11.height + 33
                        on_release: silverman11.state = "down" if silverman11.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text11
                            shorten: False
                            text: "Грудь и живот равномерно участвуют в акте дыхания"
                        MDListItemTrailingCheckbox:
                            id: silverman11
                            on_release: silverman11.state = "down" if silverman11.state == "normal" else "normal"
                            group: 'silver1'
                    MDListItem:
                        height: silver_text12.height + 33
                        on_release: silverman12.state = "down" if silverman12.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text12
                            shorten: False
                            text: "Аритмичное, неравномерное дыхание"
                        MDListItemTrailingCheckbox:
                            id: silverman12
                            on_release: silverman12.state = "down" if silverman12.state == "normal" else "normal"
                            group: 'silver1'
                    MDListItem:
                        height: silver_text13.height + 33
                        on_release: silverman13.state = "down" if silverman13.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text13
                            shorten: False
                            text: "Парадоксальное дыхание"
                        MDListItemTrailingCheckbox:
                            id: silverman13
                            on_release: silverman13.state = "down" if silverman13.state == "normal" else "normal"
                            group: 'silver1'

                SubMenuTitle:
                    text: "Втяжение межреберий"       
                MDList:
                    MDListItem:
                        height: silver_text21.height + 33
                        on_release: silverman21.state = "down" if silverman21.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text21
                            shorten: False
                            text: "Отсутствует"
                        MDListItemTrailingCheckbox:
                            id: silverman21
                            on_release: silverman21.state = "down" if silverman21.state == "normal" else "normal"
                            group: 'silver2'
                    MDListItem:
                        height: silver_text22.height + 33
                        on_release: silverman22.state = "down" if silverman22.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text22
                            shorten: False
                            text: "Нерезко выражено"
                        MDListItemTrailingCheckbox:
                            id: silverman22
                            on_release: silverman22.state = "down" if silverman22.state == "normal" else "normal"
                            group: 'silver2'
                    MDListItem:
                        height: silver_text23.height + 33
                        on_release: silverman23.state = "down" if silverman23.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text23
                            shorten: False
                            text: "Резко выражено"
                        MDListItemTrailingCheckbox:
                            id: silverman23
                            on_release: silverman23.state = "down" if silverman23.state == "normal" else "normal"
                            group: 'silver2'
                
                SubMenuTitle:
                    text: "Втяжение грудины"                
                MDList:
                    MDListItem:
                        height: silver_text31.height + 33
                        on_release: silverman31.state = "down" if silverman31.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text31
                            shorten: False
                            text: "Отсутствует"
                        MDListItemTrailingCheckbox:
                            id: silverman31
                            on_release: silverman31.state = "down" if silverman31.state == "normal" else "normal"
                            group: 'silver3'
                    MDListItem:
                        height: silver_text32.height + 33
                        on_release: silverman32.state = "down" if silverman32.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text32
                            shorten: False
                            text: "Нерезко выражено"
                        MDListItemTrailingCheckbox:
                            id: silverman32
                            on_release: silverman32.state = "down" if silverman32.state == "normal" else "normal"
                            group: 'silver3'
                    MDListItem:
                        height: silver_text33.height + 33
                        on_release: silverman33.state = "down" if silverman33.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text33
                            shorten: False
                            text: "Резко выражено, держится постоянно"
                        MDListItemTrailingCheckbox:
                            id: silverman33
                            on_release: silverman33.state = "down" if silverman33.state == "normal" else "normal"
                            group: 'silver3'

                SubMenuTitle:
                    text: "Положение нижней челюсти"               
                MDList:
                    MDListItem:
                        height: silver_text41.height + 33
                        on_release: silverman41.state = "down" if silverman41.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text41
                            shorten: False
                            text: "Рот закрыт, челюсть не западает"
                        MDListItemTrailingCheckbox:
                            id: silverman41
                            on_release: silverman41.state = "down" if silverman41.state == "normal" else "normal"
                            group: 'silver4'
                    MDListItem:
                        height: silver_text42.height + 33
                        on_release: silverman42.state = "down" if silverman42.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text42
                            shorten: False
                            text: "Рот закрыт, челюсть западает"
                        MDListItemTrailingCheckbox:
                            id: silverman42
                            on_release: silverman42.state = "down" if silverman42.state == "normal" else "normal"
                            group: 'silver4'
                    MDListItem:
                        height: silver_text43.height + 33
                        on_release: silverman43.state = "down" if silverman43.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text43
                            shorten: False
                            text: "Рот открыт, челюсть западает"
                        MDListItemTrailingCheckbox:
                            id: silverman43
                            on_release: silverman43.state = "down" if silverman43.state == "normal" else "normal"
                            group: 'silver4'

                SubMenuTitle:
                    text: "Дыхание"               
                MDList:
                    MDListItem:
                        height: silver_text51.height + 33
                        on_release: silverman51.state = "down" if silverman51.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text51
                            shorten: False
                            text: "Спокойное, ровное"
                        MDListItemTrailingCheckbox:
                            id: silverman51
                            on_release: silverman51.state = "down" if silverman51.state == "normal" else "normal"
                            group: 'silver5'
                    MDListItem:
                        height: silver_text52.height + 33
                        on_release: silverman52.state = "down" if silverman52.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text52
                            shorten: False
                            text: "При аускультации слышен затрудненный выдох"
                        MDListItemTrailingCheckbox:
                            id: silverman52
                            on_release: silverman52.state = "down" if silverman52.state == "normal" else "normal"
                            group: 'silver5'
                    MDListItem:
                        height: silver_text53.height + 33
                        on_release: silverman53.state = "down" if silverman53.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: silver_text53
                            shorten: False
                            text: "Стонущее дыхание, экспираторные шумы слышны на расстоянии"
                        MDListItemTrailingCheckbox:
                            id: silverman53
                            on_release: silverman53.state = "down" if silverman53.state == "normal" else "normal"
                            group: 'silver5'

                SubMenuTitle:
                    text: "Результат:"
                MDTextField:
                    mode: "outlined"
                    readonly: True
                    id: result
                SubMenuTitle:
                    text: "Интерпретация:"
                MDTextField:
                    mode: "outlined"
                    readonly: True
                    id: inter

        MDNavigationBar:
            MDNavigationItem:
                on_release: app.count_silverman()
                active: False
                CountBar:
            MDNavigationItem:
                on_release: app.clear_scale()
                active: False
                ClearBar:

<ScreenDownes@MDScreen>:
    name: "downes"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Шкала Даунса"
                SubMenuTitle:
                    text: "ЧД (Частота дыхания)"                    
                MDList:
                    MDListItem:
                        height: downes_text11.height + 33
                        on_release: downes11.state = "down" if downes11.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text11
                            shorten: False
                            text: "Менее 60"
                        MDListItemTrailingCheckbox:
                            id: downes11
                            on_release: downes11.state = "down" if downes11.state == "normal" else "normal"
                            group: 'downes1'
                    MDListItem:
                        height: downes_text12.height + 33
                        on_release: downes12.state = "down" if downes12.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text12
                            shorten: False
                            text: "60-80"
                        MDListItemTrailingCheckbox:
                            id: downes12
                            on_release: downes12.state = "down" if downes12.state == "normal" else "normal"
                            group: 'downes1'
                    MDListItem:
                        height: downes_text13.height + 33
                        on_release: downes13.state = "down" if downes13.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text13
                            shorten: False
                            text: "Более 80 или апноэ"
                        MDListItemTrailingCheckbox:
                            id: downes13
                            on_release: downes13.state = "down" if downes13.state == "normal" else "normal"
                            group: 'downes1'

                SubMenuTitle:
                    text: "Цианоз"               
                MDList:
                    MDListItem:
                        height: downes_text21.height + 33
                        on_release: downes21.state = "down" if downes21.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text21
                            shorten: False
                            text: "Отсутствует при дыхании комнатным воздухом"
                        MDListItemTrailingCheckbox:
                            id: downes21
                            on_release: downes21.state = "down" if downes21.state == "normal" else "normal"
                            group: 'downes2'
                    MDListItem:
                        height: downes_text22.height + 33
                        on_release: downes22.state = "down" if downes22.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text22
                            shorten: False
                            text: "Есть, исчезает при дотации кислорода до 40%"
                        MDListItemTrailingCheckbox:
                            id: downes22
                            on_release: downes22.state = "down" if downes22.state == "normal" else "normal"
                            group: 'downes2'
                    MDListItem:
                        height: downes_text23.height + 33
                        on_release: downes23.state = "down" if downes23.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text23
                            shorten: False
                            text: "Есть, исчезает при дотации кислорода более 40%"
                        MDListItemTrailingCheckbox:
                            id: downes23
                            on_release: downes23.state = "down" if downes23.state == "normal" else "normal"
                            group: 'downes2'

                SubMenuTitle:
                    text: "Втяжение грудной клетки"               
                MDList:
                    MDListItem:
                        height: downes_text31.height + 33
                        on_release: downes31.state = "down" if downes31.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text31
                            shorten: False
                            text: "Отсутствует"
                        MDListItemTrailingCheckbox:
                            id: downes31
                            on_release: downes31.state = "down" if downes31.state == "normal" else "normal"
                            group: 'downes3'
                    MDListItem:
                        height: downes_text33.height + 33
                        on_release: downes32.state = "down" if downes32.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text32
                            shorten: False
                            text: "Умеренное"
                        MDListItemTrailingCheckbox:
                            id: downes32
                            on_release: downes32.state = "down" if downes32.state == "normal" else "normal"
                            group: 'downes3'
                    MDListItem:
                        height: downes_text33.height + 33
                        on_release: downes33.state = "down" if downes33.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text33
                            shorten: False
                            text: "Значительное"
                        MDListItemTrailingCheckbox:
                            id: downes33
                            on_release: downes33.state = "down" if downes33.state == "normal" else "normal"
                            group: 'downes3'

                SubMenuTitle:
                    text: "Затрудненный выдох (стон)"           
                MDList:
                    MDListItem:
                        height: downes_text41.height + 33
                        on_release: downes41.state = "down" if downes41.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text41
                            shorten: False
                            text: "Отсутствует"
                        MDListItemTrailingCheckbox:
                            id: downes41
                            on_release: downes41.state = "down" if downes41.state == "normal" else "normal"
                            group: 'downes4'
                    MDListItem:
                        height: downes_text42.height + 33
                        on_release: downes42.state = "down" if downes42.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text42
                            shorten: False
                            text: "Выслушивается стетоскопом"
                        MDListItemTrailingCheckbox:
                            id: downes42
                            on_release: downes42.state = "down" if downes42.state == "normal" else "normal"
                            group: 'downes4'
                    MDListItem:
                        height: downes_text43.height + 33
                        on_release: downes43.state = "down" if downes43.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text43
                            shorten: False
                            text: "Слышно на расстоянии"
                        MDListItemTrailingCheckbox:
                            id: downes43
                            on_release: downes43.state = "down" if downes43.state == "normal" else "normal"
                            group: 'downes4'

                SubMenuTitle:
                    text: "Характер дыхания при аускультации"               
                MDList:
                    MDListItem:
                        height: downes_text51.height + 33
                        on_release: downes51.state = "down" if downes51.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text51
                            shorten: False
                            text: "Пуэрильное"
                        MDListItemTrailingCheckbox:
                            id: downes51
                            on_release: downes51.state = "down" if downes51.state == "normal" else "normal"
                            group: 'downes5'
                    MDListItem:
                        height: downes_text52.height + 33
                        on_release: downes52.state = "down" if downes52.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text52
                            shorten: False
                            text: "Изменено или ослаблено"
                        MDListItemTrailingCheckbox:
                            id: downes52
                            on_release: downes52.state = "down" if downes52.state == "normal" else "normal"
                            group: 'downes5'
                    MDListItem:
                        height: downes_text53.height + 33
                        on_release: downes53.state = "down" if downes53.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: downes_text53
                            shorten: False
                            text: "Плохо проводится"
                        MDListItemTrailingCheckbox:
                            id: downes53
                            on_release: downes53.state = "down" if downes53.state == "normal" else "normal"
                            group: 'downes5'

                SubMenuTitle:
                    text: "Результат:"
                MDTextField:
                    mode: "outlined"
                    readonly: True
                    id: result
                SubMenuTitle:
                    text: "Интерпретация:"
                MDTextField:
                    mode: "outlined"
                    readonly: True
                    id: inter

        MDNavigationBar:
            MDNavigationItem:
                on_release: app.count_downes()
                active: False
                CountBar:
            MDNavigationItem:
                on_release: app.clear_scale()
                active: False
                ClearBar:

<ScreenBallard@MDScreen>:
    name: "ballard"
    MDBoxLayout:
        orientation: 'vertical'
        #spacing: "12dp"

        TopMenu2:

        ScrollView:
            ScrollMenu:
                Header:
                    text: "Шкала Балларда"
                Title:
                    text: "Оценка нейромышечной зрелости новорождённого ребёнка"
                SubMenuTitle:
                    text: "Поза"
                SmartMenu:
                    height: root.width / 2
                    MDSmartTile:
                        on_release: poza_1.state = "down" if poza_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/poza/poza_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: poza_1
                                on_release: poza_1.state = "down" if poza_1.state == "normal" else "normal"
                                group: "poza"
                    MDSmartTile:
                        on_release: poza_2.state = "down" if poza_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/poza/poza_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: poza_2
                                on_release: poza_2.state = "down" if poza_2.state == "normal" else "normal"                                
                                group: "poza"
                    MDSmartTile:
                        on_release: poza_3.state = "down" if poza_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/poza/poza_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: poza_3
                                on_release: poza_3.state = "down" if poza_3.state == "normal" else "normal"
                                group: "poza"
                    MDSmartTile:
                        on_release: poza_4.state = "down" if poza_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/poza/poza_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: poza_4
                                on_release: poza_4.state = "down" if poza_4.state == "normal" else "normal"
                                #on_active: print(self, root, self.group, self.state)
                                #on_active: app.check(self)
                                group: "poza"
                    MDSmartTile:
                        on_release: poza_5.state = "down" if poza_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/poza/poza_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: poza_5
                                on_release: poza_5.state = "down" if poza_5.state == "normal" else "normal"
                                group: "poza"

                SubMenuTitle:
                    text: '"Квадратное" окно'
                SmartMenu:
                    height: root.width / 2
                    MDSmartTile:
                        on_release: squarewindow_1.state = "down" if squarewindow_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_1
                                on_release: squarewindow_1.state = "down" if squarewindow_1.state == "normal" else "normal"
                                group: "squarewindow"
                    MDSmartTile:
                        on_release: squarewindow_2.state = "down" if squarewindow_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_2
                                on_release: squarewindow_2.state = "down" if squarewindow_2.state == "normal" else "normal"                                
                                group: "squarewindow"
                    MDSmartTile:
                        on_release: squarewindow_3.state = "down" if squarewindow_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_3
                                on_release: squarewindow_3.state = "down" if squarewindow_3.state == "normal" else "normal"
                                group: "squarewindow"
                    MDSmartTile:
                        on_release: squarewindow_4.state = "down" if squarewindow_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_4
                                on_release: squarewindow_4.state = "down" if squarewindow_4.state == "normal" else "normal"
                                group: "squarewindow"
                    MDSmartTile:
                        on_release: squarewindow_5.state = "down" if squarewindow_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_5
                                on_release: squarewindow_5.state = "down" if squarewindow_5.state == "normal" else "normal"
                                group: "squarewindow"
                    MDSmartTile:
                        on_release: squarewindow_6.state = "down" if squarewindow_6.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/squarewindow/squarewindow_6.png"
                        TileContainer:
                            ImageCheckbox:
                                id: squarewindow_6
                                on_release: squarewindow_6.state = "down" if squarewindow_6.state == "normal" else "normal"
                                group: "squarewindow"
                
                SubMenuTitle:
                    text: 'Возврат руки'
                SmartMenu:
                    height: root.width / 2
                    MDSmartTile:
                        on_release: armrecoil_1.state = "down" if armrecoil_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/armrecoil/armrecoil_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: armrecoil_1
                                on_release: armrecoil_1.state = "down" if armrecoil_1.state == "normal" else "normal"
                                group: "armrecoil"
                    MDSmartTile:
                        on_release: armrecoil_2.state = "down" if armrecoil_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/armrecoil/armrecoil_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: armrecoil_2
                                on_release: armrecoil_2.state = "down" if armrecoil_2.state == "normal" else "normal"                                
                                group: "armrecoil"
                    MDSmartTile:
                        on_release: armrecoil_3.state = "down" if armrecoil_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/armrecoil/armrecoil_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: armrecoil_3
                                on_release: armrecoil_3.state = "down" if armrecoil_3.state == "normal" else "normal"
                                group: "armrecoil"
                    MDSmartTile:
                        on_release: armrecoil_4.state = "down" if armrecoil_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/armrecoil/armrecoil_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: armrecoil_4
                                on_release: armrecoil_4.state = "down" if armrecoil_4.state == "normal" else "normal"
                                group: "armrecoil"
                    MDSmartTile:
                        on_release: armrecoil_5.state = "down" if armrecoil_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/armrecoil/armrecoil_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: armrecoil_5
                                on_release: armrecoil_5.state = "down" if armrecoil_5.state == "normal" else "normal"
                                group: "armrecoil"

                SubMenuTitle:
                    text: 'Подколенный угол'
                SmartMenu:
                    height: root.width / 1.3
                    MDSmartTile:
                        on_release: angle_1.state = "down" if angle_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_1
                                on_release: angle_1.state = "down" if angle_1.state == "normal" else "normal"
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_2.state = "down" if angle_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_2
                                on_release: angle_2.state = "down" if angle_2.state == "normal" else "normal"                                
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_3.state = "down" if angle_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_3
                                on_release: angle_3.state = "down" if angle_3.state == "normal" else "normal"
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_4.state = "down" if angle_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_4
                                on_release: angle_4.state = "down" if angle_4.state == "normal" else "normal"
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_5.state = "down" if angle_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_5
                                on_release: angle_5.state = "down" if angle_5.state == "normal" else "normal"
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_6.state = "down" if angle_6.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_6.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_6
                                on_release: angle_6.state = "down" if angle_6.state == "normal" else "normal"
                                group: "angle"
                    MDSmartTile:
                        on_release: angle_7.state = "down" if angle_7.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/angle/angle_7.png"
                        TileContainer:
                            ImageCheckbox:
                                id: angle_7
                                on_release: angle_7.state = "down" if angle_7.state == "normal" else "normal"
                                group: "angle"

                SubMenuTitle:
                    text: 'Признак "шарфа"'
                SmartMenu:
	                height: root.width / 2          
                    MDSmartTile:
                        on_release: scarf_1.state = "down" if scarf_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_1
                                on_release: scarf_1.state = "down" if scarf_1.state == "normal" else "normal"
                                group: "scarf"
                    MDSmartTile:
                        on_release: scarf_2.state = "down" if scarf_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_2
                                on_release: scarf_2.state = "down" if scarf_2.state == "normal" else "normal"                                
                                group: "scarf"
                    MDSmartTile:
                        on_release: scarf_3.state = "down" if scarf_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_3
                                on_release: scarf_3.state = "down" if scarf_3.state == "normal" else "normal"
                                group: "scarf"
                    MDSmartTile:
                        on_release: scarf_4.state = "down" if scarf_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_4
                                on_release: scarf_4.state = "down" if scarf_4.state == "normal" else "normal"
                                group: "scarf"
                    MDSmartTile:
                        on_release: scarf_5.state = "down" if scarf_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_5
                                on_release: scarf_5.state = "down" if scarf_5.state == "normal" else "normal"
                                group: "scarf"
                    MDSmartTile:
                        on_release: scarf_6.state = "down" if scarf_6.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/scarf/scarf_6.png"
                        TileContainer:
                            ImageCheckbox:
                                id: scarf_6
                                on_release: scarf_6.state = "down" if scarf_6.state == "normal" else "normal"
                                group: "scarf"

                SubMenuTitle:
                    text: 'Пятка к уху'
                SmartMenu:
	                height: root.width / 2          
                    MDSmartTile:
                        on_release: heel_1.state = "down" if heel_1.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_1.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_1
                                on_release: heel_1.state = "down" if heel_1.state == "normal" else "normal"
                                group: "heel"
                    MDSmartTile:
                        on_release: heel_2.state = "down" if heel_2.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_2.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_2
                                on_release: heel_2.state = "down" if heel_2.state == "normal" else "normal"                                
                                group: "heel"
                    MDSmartTile:
                        on_release: heel_3.state = "down" if heel_3.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_3.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_3
                                on_release: heel_3.state = "down" if heel_3.state == "normal" else "normal"
                                group: "heel"
                    MDSmartTile:
                        on_release: heel_4.state = "down" if heel_4.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_4.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_4
                                on_release: heel_4.state = "down" if heel_4.state == "normal" else "normal"
                                group: "heel"
                    MDSmartTile:
                        on_release: heel_5.state = "down" if heel_5.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_5.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_5
                                on_release: heel_5.state = "down" if heel_5.state == "normal" else "normal"
                                group: "heel"
                    MDSmartTile:
                        on_release: heel_6.state = "down" if heel_6.state == "normal" else "normal"
                        MDSmartTileImage:
                            source: "image/heel/heel_6.png"
                        TileContainer:
                            ImageCheckbox:
                                id: heel_6
                                on_release: heel_6.state = "down" if heel_6.state == "normal" else "normal"
                                group: "heel"

                Title:
                    text: "Оценка физической зрелости новорождённого ребёнка"      
                SubMenuTitle:
                    text: "Кожа"               
                MDList:
                    MDListItem:
                        height: ballard_text11.height + 33
                        on_release: ballard11.state = "down" if ballard11.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text11
                            shorten: False
                            text: "Липкая, рыхлая, прозрачная"
                        MDListItemTrailingCheckbox:
                            id: ballard11
                            on_release: ballard11.state = "down" if ballard11.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text12.height + 33
                        on_release: ballard12.state = "down" if ballard12.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text12
                            shorten: False
                            text: "Желатинозная красная, прозрачная"
                        MDListItemTrailingCheckbox:
                            id: ballard12
                            on_release: ballard12.state = "down" if ballard12.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text13.height + 33
                        on_release: ballard13.state = "down" if ballard13.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text13
                            shorten: False
                            text: "Гладкая, розовая, видимые вены"
                        MDListItemTrailingCheckbox:
                            id: ballard13
                            on_release: ballard13.state = "down" if ballard13.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text14.height + 33
                        on_release: ballard14.state = "down" if ballard14.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text14
                            shorten: False
                            text: "Поверхностное шелушение, видно немного вен"
                        MDListItemTrailingCheckbox:
                            id: ballard14
                            on_release: ballard14.state = "down" if ballard14.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text15.height + 33
                        on_release: ballard15.state = "down" if ballard15.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text15
                            shorten: False
                            text: "Поверхностные трещины, редкие вены"
                        MDListItemTrailingCheckbox:
                            id: ballard15
                            on_release: ballard15.state = "down" if ballard15.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text16.height + 33
                        on_release: ballard16.state = "down" if ballard16.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text16
                            shorten: False
                            text: "Пергаментообразная, глубокие трещины, сосуды не видны"
                        MDListItemTrailingCheckbox:
                            id: ballard16
                            on_release: ballard16.state = "down" if ballard16.state == "normal" else "normal"
                            group: 'ballard1'
                    MDListItem:
                        height: ballard_text17.height + 33
                        on_release: ballard17.state = "down" if ballard17.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text17
                            shorten: False
                            text: "Зрелая, толстая, морщинистая, складчатая"
                        MDListItemTrailingCheckbox:
                            id: ballard17
                            on_release: ballard17.state = "down" if ballard17.state == "normal" else "normal"
                            group: 'ballard1'

                SubMenuTitle:
                    text: "Лануго"               
                MDList:
                    MDListItem:
                        height: ballard_text21.height + 33
                        on_release: ballard21.state = "down" if ballard21.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text21
                            shorten: False
                            text: "Нет"
                        MDListItemTrailingCheckbox:
                            id: ballard21
                            on_release: ballard21.state = "down" if ballard21.state == "normal" else "normal"
                            group: 'ballard2'
                    MDListItem:
                        height: ballard_text22.height + 33
                        on_release: ballard22.state = "down" if ballard22.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text22
                            shorten: False
                            text: "Редкое"
                        MDListItemTrailingCheckbox:
                            id: ballard22
                            on_release: ballard22.state = "down" if ballard22.state == "normal" else "normal"
                            group: 'ballard2'
                    MDListItem:
                        height: ballard_text23.height + 33
                        on_release: ballard23.state = "down" if ballard23.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text23
                            shorten: False
                            text: "Обильное"
                        MDListItemTrailingCheckbox:
                            id: ballard23
                            on_release: ballard23.state = "down" if ballard23.state == "normal" else "normal"
                            group: 'ballard2'
                    MDListItem:
                        height: ballard_text24.height + 33
                        on_release: ballard24.state = "down" if ballard24.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text24
                            shorten: False
                            text: "Необильное"
                        MDListItemTrailingCheckbox:
                            id: ballard24
                            on_release: ballard24.state = "down" if ballard24.state == "normal" else "normal"
                            group: 'ballard2'
                    MDListItem:
                        height: ballard_text25.height + 33
                        on_release: ballard25.state = "down" if ballard25.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text25
                            shorten: False
                            text: "Мало, есть области без лануго"
                        MDListItemTrailingCheckbox:
                            id: ballard25
                            on_release: ballard25.state = "down" if ballard25.state == "normal" else "normal"
                            group: 'ballard2'
                    MDListItem:
                        height: ballard_text26.height + 33
                        on_release: ballard26.state = "down" if ballard26.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text26
                            shorten: False
                            text: "Редкое, в основном кожа без лануго"
                        MDListItemTrailingCheckbox:
                            id: ballard26
                            on_release: ballard26.state = "down" if ballard26.state == "normal" else "normal"
                            group: 'ballard2'

                SubMenuTitle:
                    text: "Поверхность подошвы"               
                MDList:
                    MDListItem:
                        height: ballard_text31.height + 33
                        on_release: ballard31.state = "down" if ballard31.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text31
                            shorten: False
                            text: "Длина стопы < 40мм"
                        MDListItemTrailingCheckbox:
                            id: ballard31
                            on_release: ballard31.state = "down" if ballard31.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text32.height + 33
                        on_release: ballard32.state = "down" if ballard32.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text32
                            shorten: False
                            text: "Длина стопы 40-50мм"
                        MDListItemTrailingCheckbox:
                            id: ballard32
                            on_release: ballard32.state = "down" if ballard32.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text33.height + 33
                        on_release: ballard33.state = "down" if ballard33.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text33
                            shorten: False
                            text: ">50мм, нет складок"
                        MDListItemTrailingCheckbox:
                            id: ballard33
                            on_release: ballard33.state = "down" if ballard33.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text34.height + 33
                        on_release: ballard34.state = "down" if ballard34.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text34
                            shorten: False
                            text: "Нечёткие красные полосы"
                        MDListItemTrailingCheckbox:
                            id: ballard34
                            on_release: ballard34.state = "down" if ballard34.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text35.height + 33
                        on_release: ballard35.state = "down" if ballard35.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text35
                            shorten: False
                            text: "Заметна только передняя поперечная борозда"
                        MDListItemTrailingCheckbox:
                            id: ballard35
                            on_release: ballard35.state = "down" if ballard35.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text36.height + 33
                        on_release: ballard36.state = "down" if ballard36.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text36
                            shorten: False
                            text: "Борозды покрывают передние 2/3 стопы"
                        MDListItemTrailingCheckbox:
                            id: ballard36
                            on_release: ballard36.state = "down" if ballard36.state == "normal" else "normal"
                            group: 'ballard3'
                    MDListItem:
                        height: ballard_text37.height + 33
                        on_release: ballard37.state = "down" if ballard37.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text37
                            shorten: False
                            text: "Борозды покрывают всю стопу"
                        MDListItemTrailingCheckbox:
                            id: ballard37
                            on_release: ballard37.state = "down" if ballard37.state == "normal" else "normal"
                            group: 'ballard3'

                SubMenuTitle:
                    text: "Грудные железы"               
                MDList:
                    MDListItem:
                        height: ballard_text41.height + 33
                        on_release: ballard41.state = "down" if ballard41.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text41
                            shorten: False
                            text: "Не определяются"
                        MDListItemTrailingCheckbox:
                            id: ballard41
                            on_release: ballard41.state = "down" if ballard41.state == "normal" else "normal"
                            group: 'ballard4'
                    MDListItem:
                        height: ballard_text42.height + 33
                        on_release: ballard42.state = "down" if ballard42.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text42
                            shorten: False
                            text: "Едва определяются"
                        MDListItemTrailingCheckbox:
                            id: ballard42
                            on_release: ballard42.state = "down" if ballard42.state == "normal" else "normal"
                            group: 'ballard4'
                    MDListItem:
                        height: ballard_text43.height + 33
                        on_release: ballard43.state = "down" if ballard43.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text43
                            shorten: False
                            text: "Сосок не выражен, ареола плоская"
                        MDListItemTrailingCheckbox:
                            id: ballard43
                            on_release: ballard43.state = "down" if ballard43.state == "normal" else "normal"
                            group: 'ballard4'
                    MDListItem:
                        height: ballard_text44.height + 33
                        on_release: ballard44.state = "down" if ballard44.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text44
                            shorten: False
                            text: "Ареола чётко очерчена, диаметр железы 1-2мм"
                        MDListItemTrailingCheckbox:
                            id: ballard44
                            on_release: ballard44.state = "down" if ballard44.state == "normal" else "normal"
                            group: 'ballard4'
                    MDListItem:
                        height: ballard_text45.height + 33
                        on_release: ballard45.state = "down" if ballard45.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text45
                            shorten: False
                            text: "Ареола возвышается, диаметр железы 3-4 мм"
                        MDListItemTrailingCheckbox:
                            id: ballard45
                            on_release: ballard45.state = "down" if ballard45.state == "normal" else "normal"
                            group: 'ballard4'
                    MDListItem:
                        height: ballard_text46.height + 33
                        on_release: ballard46.state = "down" if ballard46.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text46
                            shorten: False
                            text: "Ареола полностью сформирована, диаметр железы 5-10мм"
                        MDListItemTrailingCheckbox:
                            id: ballard46
                            on_release: ballard46.state = "down" if ballard46.state == "normal" else "normal"
                            group: 'ballard4'
                
                SubMenuTitle:
                    text: "Глаз/ухо"               
                MDList:
                    MDListItem:
                        height: ballard_text51.height + 33
                        on_release: ballard51.state = "down" if ballard51.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text51
                            shorten: False
                            text: "Веки сомкнуты плотно"
                        MDListItemTrailingCheckbox:
                            id: ballard51
                            on_release: ballard51.state = "down" if ballard51.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text52.height + 33
                        on_release: ballard52.state = "down" if ballard52.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text52
                            shorten: False
                            text: "Веки сомкнуты неплотно"
                        MDListItemTrailingCheckbox:
                            id: ballard52
                            on_release: ballard52.state = "down" if ballard52.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text53.height + 33
                        on_release: ballard53.state = "down" if ballard53.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text53
                            shorten: False
                            text: "Глазки открываются, ушная раковина плоская, при сгибании остаётся нерасправленной"
                        MDListItemTrailingCheckbox:
                            id: ballard53
                            on_release: ballard53.state = "down" if ballard53.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text54.height + 33
                        on_release: ballard54.state = "down" if ballard54.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text54
                            shorten: False
                            text: "Часть ушной раковины загнута внутрь; ушная раковина мягкая, при сгибании расправляется медленно"
                        MDListItemTrailingCheckbox:
                            id: ballard54
                            on_release: ballard54.state = "down" if ballard54.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text55.height + 33
                        on_release: ballard55.state = "down" if ballard55.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text55
                            shorten: False
                            text: "Вся верхняя часть ушной раковины загнута внутрь; ушная раковина мягкая, при сгибании легко расправляется"
                        MDListItemTrailingCheckbox:
                            id: ballard55
                            on_release: ballard55.state = "down" if ballard55.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text56.height + 33
                        on_release: ballard56.state = "down" if ballard56.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text56
                            shorten: False
                            text: "Вся верхняя часть ушной раковины загнута внутрь; твёрдая, сразу же расправляется после сгибания"
                        MDListItemTrailingCheckbox:
                            id: ballard56
                            on_release: ballard56.state = "down" if ballard56.state == "normal" else "normal"
                            group: 'ballard5'
                    MDListItem:
                        height: ballard_text57.height + 33
                        on_release: ballard57.state = "down" if ballard57.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            id: ballard_text57
                            shorten: False
                            text: "Плотный хрящ; негибкая ушная раковина"
                        MDListItemTrailingCheckbox:
                            id: ballard57
                            on_release: ballard57.state = "down" if ballard57.state == "normal" else "normal"
                            group: 'ballard5'
                
                SubMenuTitle:
                    text: "Гениталии"
                MDGridLayout:
                    cols: 2
                    adaptive_height: True
                    spacing: "6dp"
                    MDCheckbox:
                        id: genit1
                        group: "genit"
                        active: True
                        on_active: app.change_genit()
                        on_press: if genit1.active == False: genit1.active = True
                    MDLabel:
                        text: "Мальчик"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                    MDCheckbox:
                        id: genit2
                        group: "genit"
                        on_active: app.change_genit()
                        on_press: if genit2.active == False: genit2.active = True 
                    MDLabel:
                        text: "Девочка"
                        adaptive_height: True
                        pos_hint: {"center_y": .5}
                MDList:
                    MDListItem:
                        height: ballard_text61.height + 33
                        on_release: ballard61.state = "down" if ballard61.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            id: ballard_text61 
                            text: "Мошонка, пустая, гладкая"
                        MDListItemTrailingCheckbox:
                            id: ballard61
                            on_release: ballard61.state = "down" if ballard61.state == "normal" else "normal"
                            group: 'ballard6'
                    MDListItem:
                        height: ballard_text62.height + 33
                        on_release: ballard62.state = "down" if ballard62.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            id: ballard_text62 
                            text: "Мошонка, пустая, незначительные складки"
                        MDListItemTrailingCheckbox:
                            id: ballard62
                            on_release: ballard62.state = "down" if ballard62.state == "normal" else "normal"
                            group: 'ballard6'
                    MDListItem:
                        height: ballard_text63.height + 33
                        on_release: ballard63.state = "down" if ballard63.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            text: "Яички расположены над входом в мошонку, редкие складки"
                            id: ballard_text63 
                        MDListItemTrailingCheckbox:
                            id: ballard63
                            on_release: ballard63.state = "down" if ballard63.state == "normal" else "normal"
                            group: 'ballard6'
                    MDListItem:
                        height: ballard_text64.height + 33
                        on_release: ballard64.state = "down" if ballard64.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            id: ballard_text64 
                            text: "Яички опускаются в мошонку (процесс не завершён), несколько складок"
                        MDListItemTrailingCheckbox:
                            id: ballard64
                            on_release: ballard64.state = "down" if ballard64.state == "normal" else "normal"
                            group: 'ballard6'
                    MDListItem:
                        height: ballard_text65.height + 33
                        on_release: ballard65.state = "down" if ballard65.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            id: ballard_text65 
                            text: "Яички опущены в мошонку, складки хорошо выражены"
                        MDListItemTrailingCheckbox:
                            id: ballard65
                            on_release: ballard65.state = "down" if ballard65.state == "normal" else "normal"
                            group: 'ballard6'
                    MDListItem:
                        height: ballard_text66.height + 33
                        on_release: ballard66.state = "down" if ballard66.state == "normal" else "normal"
                        MDListItemHeadlineText:
                            shorten: False
                            id: ballard_text66 
                            text: "Яички свободно подвешены в мошонке, хорошо выражены глубокие складки"
                        MDListItemTrailingCheckbox:
                            id: ballard66
                            on_release: ballard66.state = "down" if ballard66.state == "normal" else "normal"
                            group: 'ballard6'

                SubMenuTitle:
                    text: "Оценка нейромышленной зрелости:" 
                MDTextField:
                    id: result1
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Оценка физической зрелости:"
                MDTextField:
                    id: result2
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Общая оценка зрелости:"
                MDTextField:
                    id: resultfinal
                    mode: "outlined"
                    readonly: True
                SubMenuTitle:
                    text: "Интерпретация:"
                MDTextField:
                    mode: "outlined"
                    readonly: True
                    id: inter

        MDNavigationBar:
            MDNavigationItem:
                on_release: app.count_ballard()
                active: False
                CountBar:
            MDNavigationItem:
                on_release: app.clear_scale() ; genit1.active = True
                active: False
                ClearBar: